name: SB Engine Feature Request
description:  Your feature request for SB Engine will be help to make the SB Engine better and better.
labels: [Enhancement]
body:
  - type: textarea
    attributes:
      label: What feature do you want to get added on the SB Engine?
    validations:
      required: true
  - type: dropdown
    id: eyetest
    attributes:
      label: To test your sight, and reliability, please select the option of what should NOT be requested.
      options:
        - The missing stuff
        - The brand new .lua function's
        - Useful feature
        - Actual feedback
        - A good idea
        - New lanaguage
        - Better .lua, hxscript and more
        - Code optimization that would make the game faster. (Try to give some information's for the optimization's.)
    validations:
      required: true
