name: SB Engine help tab
description: If you need help usinng the SB Engine, you can ask any question here.
labels: [Help wanted]
body:
  - type: textarea
    id: Description
    attributes:
      label: "Describe your problem here."
    validations:
      required: true

  - type: dropdown
    id: Modding
    attributes:
      label: "Are you modding a build from source or with Lua?"
      options:
        - Lua
        - Source
    validations:
      required: true

  - type: dropdown
    id: btarget
    attributes:
      label: "What is your build target?"
      options:
        - "Android 10/11/12"
        - "Linux/Ubuntu"
        - "HTML5/Browser"
        - "Mac/Apple"
        - "Windows x32/x64/x86"
    validations:
      required: true

  - type: input
    id: buildsummary
    attributes:
      label: "Did you have the extra help here?"
      placeholder: "Yes, I have the extra help."
    validations:
      required: false
