name: Question
description: You can ask everything for the SB Engine.
labels: [Question]
body:
  - type: textarea
    attributes:
      label: Do you have any question about the SB Engine?
    validations:
      required: true
